pipeline {
  agent any
  environment {
    scannerHome = tool 'SonarQubeScanner'
  }
  tools {
    nodejs 'nodejs'
  }
  options {
    timestamps()
    timeout(time: 30, unit: 'MINUTES')
    buildDiscarder(logRotator(daysToKeepStr: '5', numToKeepStr: '10'))
  }
  stages {
    stage ('Build') {
      steps {
        sh "npm install"
      }
    }
    stage ('Sonarqube Analysis') {
      when {
        branch 'develop'
      }
      steps {
        script {
          /*
            NOTE: As per requirement, Jenkins build of develop branch doesn't have `test stage`.
            But coverage reports generated by 'npm test' command are needed by SonarQube to determine the code coverage.
            I'm running the test as a step here so the coverage report can be generated on the fly.
            It will help in keeping the github branches clean (by not pushing the coverage reports).
          */
          sh 'npm test'
          withSonarQubeEnv('Test_Sonar') {
            sh '${scannerHome}/bin/sonar-scanner'
          }
        }
      }
    }
    stage ('Test case execution') {
      when {
        branch 'master'
      }
      steps {
          sh 'npm test'
      }
    }
    stage ('Kubernetes Deployment') {
      steps {
        sh "kubectl apply -f K8s-deployment/${BRANCH_NAME}.yaml"
      }
    }
  }
  post {
    // Clean after build
    always {
      cleanWs()
    }
  }
}
